### ISSUE TITLE
Accounts.destroyToken in logout.js doesn't work

### ISSUE THREAD

**Issue by MiMaMuh** [nicolaslopezj/meteor-apollo-accounts#14]
Hi, 

I figured out that Accounts.destroyToken in your [logout function](https://github.com/nicolaslopezj/meteor-apollo-accounts/blob/master/apollo-accounts/src/Resolvers/logout.js#L7) won't destroy the token, as the method expects a hashed token hashed with `Accounts._hashLoginToken(token)`.

I tried it this way and it works - it removes the token but it throws an exception afterwards:
```
 Exception in queued task: TypeError: connection.close is not a function
     at removed (packages/accounts-base/accounts_server.js:929:22)
     at packages/mongo/observe_multiplex.js:183:30
     at Array.forEach (native)
     at Function._.each._.forEach (packages/underscore.js:139:11)
     at Object.task (packages/mongo/observe_multiplex.js:177:9)
     at [object Object]._.extend._run (packages/meteor.js:807:18)
     at packages/meteor.js:785:14
```

I haven't found a solution yet, but wanted to inform you.

**Comment by nicolaslopezj** [comment]
Nice.. I will take a look

**Comment by nicolaslopezj** [comment]
Thanks @MiMaMuh for helping to fix this
